#!/bin/bash

<<LICENSE
    Copyright (C) 2016  kevinlekiller
    
    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.
    
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
    https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html
LICENSE

<<DESCRIPTION
    Bash script for analyzing audio tracks in matroska files with BS1770GAIN and
    applying replaygain (EBU r128) track and sample peak information
    with mkvpropedit, this avoids remuxing the matroksa file.
    Pass list of files or a directory to scan files, if you pass a
    directory it will recursively search in it for files.
    It will only work on files with these extensions: "mkv, mka, mk3d".
    
    Requires: bs1770gain, mkvpropedit, file, gnu grep, which, find, tr,
              (optional) mediainfo
    
    Requires at minimum bs1770gain 0.4.11 (otherwise if the matroska file
    has multiple audio tracks, it will scan the wrong track for
    replaygain information, 0.4.11 fixes this issue).
    
    Change settings below.
    
    examples:
    ./mkvrg                  ; Recursive search in current folder for matroska files.
    ./mkvrg test.mkv         ; Process test.mkv in current folder.
    ./mkvrg Videos/          ; Recursive search in Videos folder for matroska files.
    ./mkvrg test.mkv Videos/ ; Process test.mkv in current folder and recursive
                                  search in Videos folder for matroska files.
DESCRIPTION

#########################################################################################
##################################### Settings ##########################################
#########################################################################################

# Check if the file already has tags or if tags were written succesfully, requires mediainfo.
VERIFY=false

# Force mkvrg to process matroska files, even if they already have replaygain tags. (ignored if VERIFY is false)
FORCE=false

# Minimum matroska file size to work on. change to +0 to ignore.
# For example, set to +50M to ignore files under 50MB.
MINSIZE="+0"

#########################################################################################
#########################################################################################
#########################################################################################

if [[ $VERIFY == true ]] && [[ ! $(which mediainfo) ]]; then
    echo -e "\e[31mERROR: You set verify to on but mediainfo is not installed.\e[0m"
    exit 1
fi

if [[ $(which bs1770gain) == "" ]] || [[ $(which mkvpropedit) == "" ]]; then
    echo -e "\e[31mERROR: These programs are required bs1770gain, mkvpropedit\e[0m"
    exit 1
fi

TMPFILE="$(mktemp)"

if [[ ! -f $TMPFILE ]] || [[ ! -w $TMPFILE ]]; then
    echo "\e[31mERROR: Could not create temp file $TMPFILE. Check permissions.\e[0m"
    exit 1
fi

i=0
for file in $(find "$@" -type f -size "$MINSIZE" -iregex ".*\.\(mk[av]\|mk3d\)$"); do
    if [[ ! -f $file ]]; then
        continue
    elif [[ ! $(file $file) =~ "Matroska" ]]; then
        echo -e "\e[92mNOTICE: '$file' is not a mkv file.\e[0m"
        continue
    fi
    
    if [[ ! $FORCE == true ]] && [[ $VERIFY == true ]] && [[ $(mediainfo $file) =~ "ITU-R BS.1770" ]]; then
        echo -e "\e[92mNOTICE: Skipping, replaygain tags already exist on file '$file'\e[0m"
        continue
    fi
    
    tracks=$(bs1770gain -l "$file" 2>&1 | grep -Poi "Stream\s*#\d+:\d+.+?Audio" | grep -Po "\d+:\d+" | cut -d : -f 2)

    if [[ $tracks == "" ]]; then
        echo -e "\e[93mWARNING: Could not get track list for '$file'.\e[0m"
        continue
    fi
    
    trackindex=0
    fileprocessed=0
    for track in $tracks; do
        ((trackindex++))

        echo "INFO: Running bs1770gain, this can take a while. (track $track on file '$file')"
        RGINFO=$(bs1770gain --audio "$track" --ebu -ip "$file" | tee /dev/stderr | tr "\r\n" " " | grep -Poi "[-\d.]+\s+LU.+?\[ALBUM")
        TRACKGAIN=$(echo "$RGINFO" | grep -Poi "[-\d.]+\s+LU\s+sample" | cut -d\  -f1)
        TRACKPEAK=$(echo "$RGINFO" | grep -Poi "[-\d.]+\s+\[ALBUM" | cut -d\  -f1)
        if [[ $TRACKGAIN == "" ]] || [[ $TRACKPEAK == "" ]]; then
            echo -e "\e[92mNOTICE: Problem finding replaygain info from bs1770gain for track $track on file '$file'.\e[0m"
            continue
        fi
        
        echo "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>

<!DOCTYPE Tags SYSTEM \"matroskatags.dtd\">
<Tags>
  <Tag>
    <Targets>
    </Targets>
    <Simple>
      <Name>REPLAYGAIN_TRACK_GAIN</Name>
      <String>$TRACKGAIN</String>
    </Simple>
    <Simple>
      <Name>REPLAYGAIN_TRACK_PEAK</Name>
      <String>$TRACKPEAK</String>
    </Simple>
    <Simple>
      <Name>REPLAYGAIN_ALGORITHM</Name>
      <String>ITU-R BS.1770</String>
    </Simple>
    <Simple>
      <Name>REPLAYGAIN_REFERENCE_LOUDNESS</Name>
      <String>-23.00</String>
    </Simple>
  </Tag>
</Tags>" > "$TMPFILE"
        
        echo "INFO: Applying track gain ($TRACKGAIN) / track peak ($TRACKPEAK) for track $track on file '$file'."
        
        mkvpropedit --tags track:a"$trackindex":"$TMPFILE" "$file"
        
        if [[ $VERIFY == true ]] && [[ ! $(mediainfo $file) =~ "ITU-R BS.1770" ]]; then
            echo -e "\e[93mWARNING: Replaygain has not been applied for track $track on file '$file'.\e[0m"
            continue
        fi
        ((fileprocessed++))
    done
    if [[ $fileprocessed -gt 0 ]]; then
        ((i++))
    fi
done

rm "$TMPFILE"
# If you process a single file, you can use the exit status to know if the file was processed or not,
# which is useful if you're using this script inside another script.
if [[ $i == 0 ]]; then
    exit 1
fi
